import os
import shutil
import time
from ddgs import DDGS
from ddgs.exceptions import DDGSException
from PIL import Image
import requests
from io import BytesIO

# Глобальный список уже очищенных папок
cleared_folders = set()

def download_images(query, category_folder, count=500, delay=0.5):
    folder = os.path.join("dataset", category_folder)

    # Удаляем папку только один раз
    if category_folder not in cleared_folders:
        if os.path.exists(folder):
            shutil.rmtree(folder)
        os.makedirs(folder)
        cleared_folders.add(category_folder)
    else:
        os.makedirs(folder, exist_ok=True)

    print(f"\n🔍 Searching for '{query}' images into '{folder}'...")
    with DDGS() as ddgs:
        try:
            results = ddgs.images(query, max_results=count * 3)
        except DDGSException as e:
            print(f"⚠️ Ошибка при поиске изображений: {e}")
            results = []

        downloaded = 0
        existing_files = len(os.listdir(folder))
        for i, result in enumerate(results):
            if downloaded >= count:
                break

            try:
                url = result["image"]
                response = requests.get(url, timeout=10)
                img = Image.open(BytesIO(response.content)).convert("RGB")

                filename = os.path.join(folder, f"{query.replace(' ', '_')}_{existing_files + downloaded + 1}.jpg")
                img.save(filename, format="JPEG")
                downloaded += 1
                print(f"[{downloaded}/{count}] ✅ Saved: {filename}")
                time.sleep(delay)
            except Exception as e:
                print(f"[{i + 1}] ⚠️ Failed: {e}")

    print(f"\n📁 Finished downloading {downloaded} images for '{query}' into '{folder}'")


hotdog_queries = [
    "close-up of a juicy hot dog with mustard and ketchup",
    "gourmet hot dog with caramelized onions and cheese",
    "hot dog with sauerkraut and pickles on a wooden plate",
    "grilled hot dogs on a barbecue grill",
    "hot dog with chili and melted cheddar cheese",
    "classic American hot dog in a bun with condiments",
    "hot dog with crispy bacon and jalapeños",
    "hot dog with coleslaw and barbecue sauce",
    "hot dog with avocado and spicy mayo",
    "hot dog with relish, mustard, and onions",
    "hot dog with sesame seed bun and toppings",
    "hot dog with melted cheese and crispy onions",
    "hot dog with spicy sriracha sauce and pickled veggies",
    "hot dog with fried egg and hot sauce",
    "hot dog with mac and cheese topping",
    "hot dog with grilled pineapple and teriyaki sauce",
    "hot dog with kimchi and gochujang mayo",
    "hot dog with guacamole and tortilla chips",
    "hot dog with mushrooms and Swiss cheese",
    "hot dog with buffalo sauce and blue cheese",
    "hot dog with fresh herbs and aioli",
    "hot dog with tomato slices and basil",
    "hot dog with crispy fried onions and mustard drizzle",
    "hot dog with spicy relish and cheddar",
    "hot dog with pickled red onions and arugula",
    "hot dog with curry ketchup and fries",
    "hot dog with tzatziki and cucumber",
    "hot dog with roasted peppers and feta cheese",
    "hot dog with pulled pork and barbecue sauce",
    "hot dog with scrambled eggs and cheese",
    "hot dog with spinach and garlic aioli",
    "hot dog with truffle oil and parmesan",
    "hot dog with pesto and sun-dried tomatoes",
    "hot dog with cranberry sauce and brie",
    "hot dog with spicy mango salsa",
    "hot dog with wasabi mayo and seaweed",
    "hot dog with beetroot and goat cheese",
    "hot dog with hummus and roasted veggies",
    "hot dog with sweet chili sauce and cilantro",
    "hot dog with cheddar and jalapeño poppers",
    "hot dog with bacon-wrapped sausage",
    "hot dog with double sausage and cheese",
    "hot dog with grilled zucchini and pesto",
    "hot dog with spicy peanut sauce and cucumber",
    "hot dog with horseradish cream and dill",
    "hot dog with cranberry mustard and turkey sausage",
    "hot dog with maple syrup and bacon",
    "hot dog with cheddar-stuffed sausage",
    "hot dog with fried pickles and ranch",
    "hot dog with spicy tomato chutney and onions",
    "hot dog with onion rings and barbecue drizzle",
    "hot dog with melted mozzarella and marinara sauce",
    "hot dog with jalapeño cream cheese and bacon bits",
    "hot dog with roasted garlic and herb butter",
    "hot dog with chipotle mayo and grilled corn",
    "hot dog with pickled jalapeños and cheddar sauce",
    "hot dog with spicy Thai peanut slaw",
    "hot dog with pineapple salsa and cilantro",
    "hot dog with teriyaki glaze and sesame seeds",
    "hot dog with spicy curry sauce and onions",
    "hot dog with dill pickles and spicy mustard",
    "hot dog with roasted tomato and basil pesto",
    "hot dog with caramelized onions and balsamic glaze",
    "hot dog with spicy kimchi and sesame mayo",
    "hot dog with cheddar cheese and crispy bacon",
    "hot dog with jalapeño relish and sour cream",
    "hot dog with spicy aioli and fried onions",
    "hot dog with barbecue pulled chicken topping",
    "hot dog with creamy coleslaw and hot sauce",
    "hot dog with spicy avocado crema and cilantro",
    "hot dog with grilled mushrooms and garlic butter",
    "hot dog with spicy chipotle ketchup and pickles",
    "hot dog with roasted red peppers and feta",
    "hot dog with spicy mango chutney and mint",
    "hot dog with creamy spinach and artichoke topping",
    "hot dog with spicy buffalo chicken and ranch",
    "hot dog with grilled onions and cheddar sauce",
    "hot dog with spicy jalapeño slaw and mustard",
    "hot dog with crispy tortilla strips and salsa",
    "hot dog with spicy habanero sauce and onions",
    "hot dog with creamy garlic aioli and herbs",
    "hot dog with spicy tomato salsa and avocado",
    "hot dog with grilled eggplant and tahini sauce",
    "hot dog with spicy mustard and sauerkraut",
    "hot dog with roasted corn and chipotle mayo",
    "hot dog with spicy barbecue beans and cheese",
    "hot dog with creamy avocado and lime drizzle",
    "hot dog with spicy pickled onions and jalapeños",
    "hot dog with grilled bell peppers and pesto",
    "hot dog with spicy ranch and crispy bacon",
    "hot dog with creamy cheese sauce and chili flakes",
    "hot dog with spicy tomato relish and herbs",
    "hot dog with grilled pineapple and spicy glaze",
    "hot dog with spicy garlic sauce and pickles",
    "hot dog with creamy jalapeño dip and chips",
    "hot dog with spicy tomato cream and basil",
    "hot dog with grilled asparagus and lemon aioli",
    "hot dog with spicy chipotle cream and cilantro",
    "hot dog with roasted sweet potatoes and feta",
    "hot dog with spicy avocado salsa and lime",
    "hot dog with grilled peaches and honey mustard",
    "hot dog with spicy tomato jam and goat cheese",
    "hot dog with crispy onions and spicy ketchup"
]

more_hotdog_queries = [
  "vegan hot dog with grilled tofu and avocado",
  "hot dog with spicy jalapeño ketchup and crispy onions",
  "hot dog with cheddar cheese and caramelized apples",
  "hot dog with roasted garlic aioli and microgreens",
  "hot dog with spicy chipotle slaw and lime",
  "hot dog with beer cheese sauce and pretzel bun",
  "hot dog with pickled carrots and daikon",
  "hot dog with spicy mustard and crushed potato chips",
  "hot dog with creamy dill sauce and cucumber ribbons",
  "hot dog with bacon jam and arugula",
  "hot dog with spicy gochujang glaze and sesame slaw",
  "hot dog with grilled halloumi and mint yogurt",
  "hot dog with spicy chimichurri and roasted peppers",
  "hot dog with creamy tzatziki and olives",
  "hot dog with spicy Cajun remoulade and shrimp",
  "hot dog with roasted beet slaw and goat cheese",
  "hot dog with spicy curry mayo and mango chutney",
  "hot dog with crispy shallots and garlic aioli",
  "hot dog with spicy tomato relish and feta",
  "hot dog with creamy horseradish sauce and pickled radish",
  "hot dog with spicy jalapeño jelly and cream cheese",
  "hot dog with grilled corn salsa and lime crema",
  "hot dog with spicy Thai basil sauce and peanuts",
  "hot dog with roasted eggplant and harissa",
  "hot dog with spicy honey mustard and bacon bits",
  "hot dog with creamy avocado ranch and scallions",
  "hot dog with spicy tomato salsa and queso fresco",
  "hot dog with grilled peach chutney and prosciutto",
  "hot dog with spicy garlic butter and parmesan",
  "hot dog with creamy chipotle sauce and black beans",
  "hot dog with spicy pineapple glaze and cilantro",
  "hot dog with roasted jalapeños and cheddar drizzle",
  "hot dog with spicy maple mustard and crispy onions",
  "hot dog with creamy spinach dip and bacon",
  "hot dog with spicy tomato cream and basil pesto",
  "hot dog with grilled mango and chili lime sauce",
  "hot dog with spicy peanut butter and sriracha",
  "hot dog with creamy hummus and za'atar",
  "hot dog with spicy avocado salsa and tortilla strips",
  "hot dog with roasted garlic spread and sun-dried tomatoes",
  "hot dog with spicy ranch drizzle and fried onions",
  "hot dog with creamy buffalo sauce and celery",
  "hot dog with spicy tomato jam and crispy pancetta",
  "hot dog with grilled watermelon and feta",
  "hot dog with spicy mustard glaze and pickled jalapeños",
  "hot dog with creamy pesto aioli and roasted tomatoes",
  "hot dog with spicy chipotle cream and grilled onions",
  "hot dog with roasted squash and sage butter",
  "hot dog with spicy tomato chutney and mint yogurt",
  "hot dog with creamy cheese fondue and bacon",
  "hot dog with spicy mango salsa and lime crema",
  "hot dog with grilled figs and balsamic glaze",
  "hot dog with spicy garlic mayo and pickled cabbage",
  "hot dog with creamy avocado dip and roasted corn",
  "hot dog with spicy tomato sauce and mozzarella",
  "hot dog with grilled apple slices and cinnamon mustard",
  "hot dog with spicy jalapeño cream and cheddar",
  "hot dog with creamy spinach and roasted garlic",
  "hot dog with spicy chipotle glaze and crispy bacon",
  "hot dog with grilled banana peppers and ranch",
  "hot dog with spicy tomato aioli and arugula",
  "hot dog with creamy feta spread and olives",
  "hot dog with spicy chili flakes and garlic butter",
  "hot dog with grilled sweet peppers and provolone",
  "hot dog with spicy avocado crema and pickled onions",
  "hot dog with creamy jalapeño sauce and crushed chips",
  "hot dog with spicy tomato relish and fresh basil",
  "hot dog with grilled mushrooms and truffle mayo",
  "hot dog with spicy barbecue glaze and cheddar",
  "hot dog with creamy garlic dip and roasted peppers",
  "hot dog with spicy mustard and crispy shallots",
  "hot dog with grilled pineapple rings and teriyaki drizzle",
  "hot dog with spicy tomato salsa and sour cream",
  "hot dog with creamy chipotle ranch and bacon bits",
  "hot dog with spicy mango chutney and cilantro",
  "hot dog with grilled zucchini and garlic aioli",
  "hot dog with spicy jalapeño slaw and cheddar",
  "hot dog with creamy avocado spread and lime zest",
  "hot dog with spicy tomato glaze and crispy onions",
  "hot dog with grilled peaches and spicy honey",
  "hot dog with spicy garlic sauce and pickled veggies",
  "hot dog with creamy cheese sauce and jalapeño rings",
  "hot dog with spicy tomato cream and roasted garlic",
  "hot dog with grilled asparagus and lemon butter",
  "hot dog with spicy chipotle drizzle and corn salsa",
  "hot dog with roasted sweet potatoes and chili flakes",
  "hot dog with spicy avocado salsa and mint",
  "hot dog with grilled nectarines and balsamic glaze",
  "hot dog with spicy tomato jam and crispy prosciutto",
  "hot dog with creamy jalapeño dip and scallions",
  "hot dog with spicy tomato chutney and goat cheese",
  "hot dog with grilled eggplant and spicy tahini",
  "hot dog with spicy mustard and pickled cucumbers",
  "hot dog with roasted corn and creamy chipotle sauce",
  "hot dog with spicy barbecue beans and cheddar",
  "hot dog with creamy avocado drizzle and cilantro",
  "hot dog with spicy pickled onions and garlic aioli",
  "hot dog with grilled bell peppers and spicy pesto",
  "hot dog with spicy ranch and crispy shallots",
  "hot dog with creamy cheese sauce and chili oil",
  "hot dog with spicy tomato relish and fresh herbs",
  "hot dog with grilled pineapple and spicy teriyaki",
  "hot dog with spicy garlic glaze and pickled jalapeños",
  "hot dog with creamy jalapeño dip and tortilla strips",
  "hot dog with spicy tomato cream and fresh basil",
  "hot dog with grilled asparagus and spicy lemon aioli",
  "hot dog with spicy chipotle cream and roasted corn",
  "hot dog with roasted sweet potatoes and spicy feta",
  "hot dog with spicy avocado salsa and lime zest",
  "hot dog with grilled peaches and spicy mustard glaze",
  "hot dog with spicy tomato jam and creamy goat cheese",
  "hot dog with crispy onions and spicy ketchup drizzle"
]


not_hotdog_queries = [
    "close-up of a grilled cheese sandwich",
    "Italian pizza with pepperoni and olives",
    "shawarma wrap with vegetables and sauce",
    "croissant sandwich with ham and cheese",
    "bagel sandwich with smoked salmon and cream cheese",
    "turkey club sandwich with bacon and lettuce",
    "panini with mozzarella, tomato, and basil",
    "falafel wrap with tahini and salad",
    "burrito with rice, beans, and guacamole",
    "quesadilla with melted cheese and salsa",
    "taco with beef, lettuce, and cheese",
    "kebab on a skewer with grilled vegetables",
    "meat pie with golden crust",
    "stuffed pita bread with hummus and veggies",
    "grilled chicken sandwich with mayo and lettuce",
    "vegan wrap with tofu and avocado",
    "sub sandwich with salami and provolone",
    "breakfast sandwich with egg and sausage",
    "cheesesteak sandwich with onions and peppers",
    "naan wrap with curry chicken",
    "open-faced sandwich with egg salad",
    "toasted sandwich with turkey and cranberry",
    "wrap with grilled shrimp and mango salsa",
    "gyro with lamb and tzatziki sauce",
    "sushi rolls with salmon and avocado",
    "bánh mì sandwich with pork and pickled vegetables",
    "grilled veggie sandwich with hummus",
    "chicken Caesar wrap with parmesan",
    "pita pocket with falafel and lettuce",
    "eggplant parmesan sandwich",
    "meatball sub with marinara and mozzarella",
    "roast beef sandwich with horseradish sauce",
    "chicken tikka wrap with yogurt sauce",
    "tuna melt sandwich with cheddar",
    "BLT sandwich with crispy bacon",
    "caprese sandwich with tomato and mozzarella",
    "grilled halloumi wrap with veggies",
    "chicken schnitzel sandwich",
    "veggie burger with lettuce and tomato",
    "fish sandwich with tartar sauce",
    "pulled pork sandwich with coleslaw",
    "chicken pesto panini",
    "egg and cheese breakfast wrap",
    "avocado toast with poached egg",
    "muffuletta sandwich with olive salad",
    "reuben sandwich with corned beef",
    "pastrami sandwich with mustard",
    "shrimp po' boy sandwich",
    "chicken gyro with pita bread",
    "grilled tofu sandwich with spicy mayo",
    "stuffed bell peppers with rice and meat",
    "lasagna with layers of pasta, meat, and cheese",
    "spaghetti carbonara with bacon and parmesan",
    "fettuccine alfredo with creamy sauce",
    "chicken parmesan with marinara and mozzarella",
    "beef stew with potatoes and carrots",
    "chicken curry with rice and naan",
    "vegetable stir fry with noodles",
    "fried rice with shrimp and vegetables",
    "pad thai with peanuts and lime",
    "ramen bowl with pork and egg",
    "pho soup with beef and herbs",
    "udon noodles with tempura",
    "bibimbap with vegetables and egg",
    "dim sum dumplings in bamboo steamer",
    "spring rolls with dipping sauce",
    "samosas with spicy filling",
    "stuffed cabbage rolls with tomato sauce",
    "pierogi with potato and cheese",
    "gnocchi with tomato basil sauce",
    "risotto with mushrooms and parmesan",
    "stuffed zucchini boats with cheese",
    "grilled salmon with lemon and herbs",
    "baked cod with garlic butter",
    "shrimp scampi with linguine",
    "crab cakes with remoulade sauce",
    "lobster tail with melted butter",
    "clam chowder in a bread bowl",
    "ceviche with lime and cilantro",
    "tuna tartare with avocado",
    "grilled steak with mashed potatoes",
    "barbecue ribs with corn on the cob",
    "roast chicken with vegetables",
    "lamb chops with rosemary",
    "duck breast with cherry sauce",
    "stuffed chicken breast with spinach",
    "beef Wellington with puff pastry",
    "pork tenderloin with apple glaze",
    "chicken fajitas with peppers",
    "beef tacos with salsa",
    "enchiladas with red sauce",
    "chilaquiles with eggs and cheese",
    "tamales with pork filling",
    "empanadas with beef and olives",
    "arepas with cheese and meat",
    "pupusas with beans and cheese",
    "cornbread with honey butter",
    "stuffed mushrooms with cheese",
    "deviled eggs with paprika",
    "bruschetta with tomato and basil",
    "caprese salad with balsamic glaze",
    "Greek salad with feta and olives",
    "Caesar salad with croutons",
    "cobb salad with bacon and avocado"
]

more_not_hotdog_queries = [
  "grilled cheese panini with tomato soup",
  "vegan burrito bowl with quinoa and black beans",
  "stuffed avocado halves with tuna salad",
  "creamy mushroom risotto with parmesan",
  "chicken shawarma plate with garlic sauce",
  "beef bulgogi with steamed rice and kimchi",
  "vegetarian sushi rolls with cucumber and avocado",
  "shrimp tacos with cabbage slaw and lime crema",
  "grilled lamb kebabs with yogurt dip",
  "chicken enchiladas with green sauce",
  "spicy ramen bowl with soft-boiled egg",
  "grilled portobello burger with pesto",
  "stuffed sweet potatoes with black beans and cheese",
  "chicken satay skewers with peanut sauce",
  "vegan chili with cornbread",
  "grilled eggplant stack with mozzarella and tomato",
  "salmon poke bowl with edamame and rice",
  "beef stroganoff with egg noodles",
  "chicken teriyaki bowl with steamed broccoli",
  "vegetable curry with coconut rice",
  "stuffed bell peppers with quinoa and lentils",
  "grilled chicken Caesar salad wrap",
  "spicy Thai noodle salad with peanuts",
  "baked ziti with ricotta and marinara",
  "chicken and waffles with maple syrup",
  "grilled cheese sandwich with caramelized onions",
  "vegan lentil loaf with mashed potatoes",
  "shrimp fried rice with scallions",
  "chicken tortilla soup with avocado",
  "grilled steak fajitas with peppers",
  "vegetarian lasagna with spinach and ricotta",
  "beef empanadas with chimichurri",
  "chicken pot pie with flaky crust",
  "grilled salmon salad with citrus vinaigrette",
  "stuffed mushrooms with spinach and feta",
  "chicken tikka masala with basmati rice",
  "vegetable pad see ew with tofu",
  "spicy black bean burger with avocado",
  "grilled chicken gyro with cucumber sauce",
  "beef burrito with sour cream and salsa",
  "vegetarian paella with artichokes and peas",
  "chicken quesadilla with pico de gallo",
  "grilled shrimp skewers with lemon butter",
  "vegan stir fry with broccoli and cashews",
  "chicken Alfredo pasta with garlic bread",
  "grilled vegetable wrap with hummus",
  "beef chili with cheddar and sour cream",
  "spicy soba noodles with sesame dressing",
  "grilled turkey sandwich with cranberry mayo",
  "vegan sushi bowl with pickled ginger",
  "chicken curry wrap with mango chutney",
  "grilled tofu tacos with avocado crema",
  "beef gyro plate with rice and salad",
  "vegetarian stuffed eggplant with tomato sauce",
  "chicken burrito bowl with corn and beans",
  "grilled cheese toastie with tomato chutney",
  "spicy Thai curry noodles with basil",
  "grilled chicken wrap with chipotle mayo",
  "vegan falafel bowl with tahini drizzle",
  "shrimp pasta with garlic cream sauce",
  "grilled veggie panini with balsamic glaze",
  "chicken Caesar salad with croutons",
  "beef stew with crusty bread",
  "grilled fish tacos with mango salsa",
  "vegetarian enchiladas with mole sauce",
  "chicken shawarma wrap with pickles",
  "grilled halloumi salad with pomegranate",
  "vegan burrito with sweet potatoes and kale",
  "chicken tikka wrap with mint yogurt",
  "grilled steak sandwich with horseradish",
  "vegetarian ramen with miso broth",
  "shrimp po' boy with spicy remoulade",
  "grilled chicken sandwich with pesto",
  "vegan pasta primavera with cashew cream",
  "chicken gyro wrap with tzatziki",
  "grilled veggie burger with avocado",
  "beef taco salad with tortilla strips",
  "chicken enchilada casserole",
  "grilled salmon wrap with dill sauce",
  "vegetarian chili with cornbread muffins",
  "chicken teriyaki stir fry with rice",
  "grilled tofu sandwich with spicy slaw",
  "beef burrito with jalapeño cheese",
  "vegan wrap with roasted vegetables",
  "chicken Caesar wrap with parmesan",
  "grilled shrimp salad with citrus dressing",
  "vegetarian quesadilla with mushrooms",
  "chicken tikka bowl with naan",
  "grilled steak tacos with chimichurri",
  "vegan lentil curry with basmati rice",
  "chicken fajita wrap with peppers",
  "grilled veggie sandwich with goat cheese",
  "shrimp stir fry with noodles",
  "vegetarian sushi rolls with mango",
  "chicken shawarma bowl with rice",
  "grilled tofu wrap with peanut sauce",
  "beef empanadas with spicy salsa",
  "vegan burger with spicy mayo",
  "grilled chicken salad with avocado",
  "vegetarian lasagna with zucchini",
  "shrimp tacos with chipotle crema",
  "chicken wrap with ranch and bacon",
  "grilled veggie wrap with pesto",
  "beef burrito bowl with guacamole",
  "vegan stir fry with sesame sauce",
  "chicken quesadilla with jalapeños"
]

# Download images
# for query in hotdog_queries:
#     download_images(query, "hotdog", count=500)

for query in more_hotdog_queries:
    download_images(query, "hotdog", count=500)

# for query in not_hotdog_queries:
#    download_images(query, "not_hotdog", count=500)

for query in more_not_hotdog_queries:
    download_images(query, "not_hotdog", count=500)